name: Lesboland
favicon: null
layout_spectrum: 0.76727
typography_spectrum: 0.8323417669162154
title: LESBOLAND
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02afd1'
    - '#d1d5d8'
    - '#2b2f32'
    - '#a4a7aa'
    - '#707075'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
