name: Lesboland
favicon: null
layout_spectrum: 0.76727
typography_spectrum: 0.8323417669162154
title: LESBOLAND
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2232a'
    - '#6bcde7'
    - '#fff200'
    - '#ffffff'
    - '#eba0a3'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
