name: Lesboland
favicon: null
layout_spectrum: 0.13430833769962192
typography_spectrum: 0.8323417669162154
title: Best Seller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06270632101222873
  lightness: 0.6805088059045374
  saturation: 0.3640221410896629
  rhythmicContrast: 0.35372439539059997
purpose: []
