name: Lesboland
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8323417669162154
title: LESBOLAND
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2232a'
    - '#6bcde7'
    - '#fff200'
    - '#ffffff'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
